# Generated by Django 2.1.5 on 2020-03-28 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import places.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'patient'), (2, 'doctor'), (3, 'hospital'), (4, 'admin')], default=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=140)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('regid', models.CharField(max_length=60, unique=True)),
                ('dname', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'male'), (1, 'female'), (2, 'not specified')])),
                ('spec', models.CharField(blank=True, max_length=50)),
                ('hos', models.CharField(blank=True, max_length=150)),
                ('imagefile', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='doctor/')),
                ('location', places.fields.PlacesField(max_length=255)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('regid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('spec', models.TextField(blank=True)),
                ('services', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('url', models.URLField(blank=True)),
                ('imagefile', models.ImageField(blank=True, null=True, upload_to='hospital/')),
                ('location', places.fields.PlacesField(max_length=255)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('permission', models.CharField(blank=True, choices=[('public', 'public'), ('private', 'private'), ('custom', 'custom')], max_length=10)),
                ('access', models.CharField(blank=True, max_length=100)),
                ('diagnosis', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=100), size=None)),
                ('procedures', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=100), size=None)),
                ('prescription', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=100), size=None)),
                ('description', models.TextField(blank=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='Visit Date')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Doctor', verbose_name='doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('regid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pname', models.CharField(max_length=50)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'male'), (1, 'female'), (2, 'not specified')])),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('bloodgroup', models.CharField(blank=True, choices=[('apos', 'A+'), ('aneg', 'A-'), ('bpos', 'B+'), ('bneg', 'B-'), ('opos', 'O+'), ('oneg', 'O-'), ('abpos', 'AB+'), ('abneg', 'AB-'), ('unspecified', '-')], default='-', max_length=12)),
                ('place', models.CharField(blank=True, max_length=50)),
                ('imagefile', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='patient/')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'like'), (0, 'dislike')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Patient', verbose_name='patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Doctor', verbose_name='doctor')),
            ],
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Patient', verbose_name='patient'),
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Post'),
        ),
    ]
