# Generated by Django 2.1.5 on 2020-03-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='permission',
            field=models.CharField(blank=True, choices=[('public', 'public'), ('private', 'private'), ('custom', 'custom')], max_length=10),
        ),
    ]
