# Generated by Django 2.1.5 on 2020-03-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200325_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='access',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
