# Generated by Django 2.1.5 on 2020-04-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='spec',
            field=models.CharField(choices=[('Hypertensiology', 'Hypertensiology'), ('Surgery', 'Surgery'), ('Gastroenterology', 'Gastroenterology'), ('Traumatology', 'Traumatology'), ('Ophthalmology', 'Ophthalmology'), ('Toxicology', 'Toxicology'), ('Orthopedics', 'Orthopedics'), ('Dermatology', 'Dermatology'), ('Infectiology', 'Infectiology'), ('Endocrinology', 'Endocrinology'), ('Pulmonology', 'Pulmonology'), ('Urology', 'Urology'), ('Cardiology', 'Cardiology'), ('Nephrology', 'Nephrology'), ('Hematology', 'Hematology'), ('Laryngology/ENT', 'Laryngology/ENT'), ('Gynecology', 'Gynecology'), ('Psychiatry', 'Psychiatry'), ('Oncology', 'Oncology'), ('Allergology', 'Allergology'), ('Neurology', 'Neurology'), ('Rheumatology', 'Rheumatology'), ('Venereology', 'Venereology'), ('Angiology', 'Angiology'), ('Internal Medicine', 'Internal Medicine'), ('Other', 'Other'), ('Dentistry', 'Dentistry'), ('Diabetology', 'Diabetology')], default='Other', max_length=50),
        ),
    ]
