# Generated by Django 2.1.5 on 2020-03-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200325_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Patient', verbose_name='patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Doctor', verbose_name='doctor')),
            ],
        ),
    ]
