# Generated by Django 2.1.5 on 2020-03-27 07:05

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('likes', django_mysql.models.ListCharField(models.CharField(blank=True, max_length=10), max_length=1000, size=None)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Doctor')),
            ],
        ),
    ]
