# Generated by Django 2.1.5 on 2020-04-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=150, null=True)),
                ('date_start', models.CharField(blank=True, max_length=25, null=True)),
                ('date_end', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Doctor')),
            ],
        ),
    ]
