# Generated by Django 2.1.5 on 2020-05-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
