# Generated by Django 2.1.5 on 2020-05-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200526_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
