# Generated by Django 2.1.5 on 2020-06-01 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('procedure', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='labrecords/')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Visit Date')),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'patient'), (2, 'doctor'), (3, 'hospital'), (4, 'admin'), (5, 'laboratory')], default=4),
        ),
        migrations.AddField(
            model_name='laboratoryrecord',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='laboratory'),
        ),
        migrations.AddField(
            model_name='laboratoryrecord',
            name='medrec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.MedicalRecord'),
        ),
        migrations.AddField(
            model_name='laboratoryrecord',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Patient', verbose_name='patient'),
        ),
    ]
