# Generated by Django 2.1.5 on 2020-06-02 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20200602_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryrecord',
            name='lab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Laboratory', verbose_name='laboratory'),
        ),
    ]
